update pipeline for managing multiple tags for docker image

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,20 +20,14 @@ jobs:
       - name: Install xmllint
         run: sudo apt-get update && sudo apt-get install -y libxml2-utils
 
-      - name: Extract release version from pom.xml (excluding parent/version)
-        id: extract-version
+      - name: Extract and print version from pom.xml
         run: |
-          # Utilizza xmllint per estrarre la versione principale del progetto, che si trova in /project/version.
-          # In questo modo si esclude automaticamente la versione definita all'interno di <parent>.
-          RELEASE_VERSION=$(xmllint --xpath "string(/project/version)" pom.xml | sed 's/-SNAPSHOT//')
-          if [ -z "$RELEASE_VERSION" ]; then
-              echo "ERROR: Version not found or not in expected format."
-              exit 1
+          VERSION=$(xmllint --xpath "string(/project/version)" pom.xml)
+          if [ -z "$VERSION" ]; then
+            echo "ERROR: Version not found or not in expected format."
+            exit 1
           fi
-          echo "Release version is $RELEASE_VERSION"
-          # Esporta la variabile in ambiente globale per gli step successivi
-          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
-
+          echo "Extracted version: $VERSION"
 
       - name: Set up Java 21
         uses: actions/setup-java@v3
